@extends('layouts.public.layout')

@section('content')

<!-- Hero Header Section -->
<section class="hero-bg relative h-screen md:h-[75vh] flex items-center justify-center text-white overflow-hidden -mt-20">
  <div class="relative z-10 text-center px-4 max-w-4xl mx-auto">
    <h1 class="text-5xl md:text-7xl lg:text-8xl font-bold font-serif leading-tight drop-shadow-2xl mb-4 animate-fade-in-down">
      Galeri <span class="text-transparent bg-clip-text bg-gradient-to-r from-emerald-300 to-teal-200">Foto</span>
    </h1>
    <p class="text-lg md:text-2xl text-slate-100 drop-shadow-md animate-fade-in-up">Koleksi momen-momen berharga kegiatan desa</p>
  </div>
  <!-- Scroll Down Indicator -->
  <div class="absolute bottom-10 left-1/2 transform -translate-x-1/2 animate-smooth-lucid-mouse opacity-80 cursor-pointer hover:opacity-100 hover:text-emerald-300 transition-all duration-300">
    <a href="#galeri-list"><i data-lucide="mouse" class="w-8 h-8"></i></a>
  </div>
</section>

<div class="bg-slate-50 antialiased text-slate-600" id="galeri-list">
  <!-- Main Content -->
  <div class="container mx-auto px-6 py-12">

    <!-- Filter Buttons -->
    <div class="flex flex-wrap justify-center gap-4 mb-12" data-aos="fade-up" data-aos-delay="100">
      <button class="filter-btn is-active px-6 py-2 rounded-full font-medium border transition-all duration-300" data-filter="all">Semua</button>
      <button class="filter-btn px-6 py-2 rounded-full font-medium border transition-all duration-300" data-filter="kegiatan">Kegiatan</button>
      <button class="filter-btn px-6 py-2 rounded-full font-medium border transition-all duration-300" data-filter="alam">Alam & Wisata</button>
      <button class="filter-btn px-6 py-2 rounded-full font-medium border transition-all duration-300" data-filter="pembangunan">Pembangunan</button>
    </div>

    <!-- Gallery Grid - 3 columns -->
    <div class="gallery-grid" id="gallery-container">
      @forelse($galeris as $index => $galeri)
        @php
          $category = strtolower($galeri->kategori ?? 'kegiatan');
          // Map kategori to filter keys
          $categoryMap = [
            'kegiatan' => 'kegiatan',
            'alam & wisata' => 'alam',
            'pembangunan' => 'pembangunan',
          ];
          $categorySlug = $categoryMap[$category] ?? 'kegiatan';
        @endphp
        <div class="gallery-item group relative rounded-xl overflow-hidden shadow-lg cursor-pointer hover:shadow-2xl transition-all duration-300" 
             data-aos="fade-up" 
             data-aos-delay="{{ ($index % 3) * 100 }}"
             data-category="{{ $categorySlug }}"
             data-id="{{ $galeri->id }}"
             onclick="openModal({{ $galeri->id }})">
          <div class="relative overflow-hidden bg-slate-200 h-64 sm:h-72">
            <img src="{{ asset('storage/' . $galeri->gambar) }}" 
                 class="w-full h-full object-cover transform transition-all duration-500 group-hover:scale-110 group-hover:blur-sm" 
                 alt="{{ $galeri->judul }}">
            
            <!-- Overlay Tupoksi (Hover) -->
            <div 
              class="absolute inset-0 flex flex-col justify-center items-center p-6 text-center opacity-0 group-hover:opacity-100 transition-all duration-300 transform translate-y-4 group-hover:translate-y-0"
              style="background: linear-gradient(135deg, rgba(0,0,0,0.85) 0%, rgba(20,20,30,0.9) 100%);">
              <div class="w-10 h-10 bg-white/10 rounded-full flex items-center justify-center mb-3">
                <i data-lucide="image" class="w-5 h-5 text-emerald-400"></i>
              </div>
              <h4 class="text-white font-bold text-lg mb-2">{{ $galeri->judul }}</h4>
              <div class="text-sm leading-relaxed text-white/90">
                @if($galeri->deskripsi)
                  {{ Str::limit($galeri->deskripsi, 80) }}
                @else
                  <p class="italic">Deskripsi tidak tersedia</p>
                @endif
              </div>
            </div>
          </div>

          <!-- Info Card (Below Image) -->
          <div class="p-6 text-center relative flex flex-col items-center justify-center min-h-24 bg-white">
            <span class="text-emerald-600 text-xs font-bold uppercase tracking-wider mb-2">{{ $galeri->kategori }}</span>
            <h3 class="text-slate-800 font-bold line-clamp-2">{{ $galeri->judul }}</h3>
          </div>
        </div>
      @empty
        <div class="col-span-full text-center py-12">
          <div class="text-slate-400 mb-4">
            <i class="fas fa-image text-4xl"></i>
          </div>
          <p class="text-slate-600 text-lg">Belum ada foto galeri</p>
        </div>
      @endforelse
    </div>

    <!-- Pagination -->
    <nav class="pagination" aria-label="Pagination" id="pagination-container">
      <!-- Pagination will be generated by JavaScript -->
    </nav>
  </div>
</div>

<!-- Gallery data for JavaScript (injected as JSON) -->
<script type="application/json" id="galery-data">
{!! json_encode($galeris->map(function($g) {
  return [
    'id' => $g->id,
    'judul' => $g->judul,
    'gambar' => asset('storage/' . $g->gambar),
    'deskripsi' => $g->deskripsi,
    'kategori' => $g->kategori,
    'created_at' => $g->created_at->format('d M Y'),
  ];
})->values()->all()) !!}
</script>

<!-- Modal Lightbox -->
<div id="imageModal" class="modal">
  <div class="modal-content">
    <!-- Modal Header -->
    <div class="modal-header">
      <h2 id="modalTitle" class="text-xl font-bold text-slate-900"></h2>
      <span class="close-modal" onclick="closeModal()">&times;</span>
    </div>

    <!-- Modal Body -->
    <div class="modal-body">
      <img id="modalImage" src="" alt="" class="modal-image">
      
      <div class="space-y-4">
        <div>
          <p class="text-xs font-semibold text-emerald-600 uppercase tracking-wide mb-1">Kategori</p>
          <p id="modalCategory" class="text-sm text-slate-600"></p>
        </div>
        
        <div>
          <p class="text-xs font-semibold text-emerald-600 uppercase tracking-wide mb-1">Deskripsi</p>
          <p id="modalDescription" class="text-sm text-slate-700 leading-relaxed"></p>
        </div>

        <div class="grid grid-cols-2 gap-4 text-sm">
          <div>
            <p class="text-xs font-semibold text-emerald-600 uppercase tracking-wide mb-1">Tanggal Upload</p>
            <p id="modalDate" class="text-slate-600"></p>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal Footer -->
    <div class="modal-footer">
      <button onclick="downloadImage()" class="modal-action modal-action-primary">
        <i data-lucide="download" class="w-4 h-4"></i> Unduh
      </button>
      <button onclick="prevImage()" class="modal-action modal-action-secondary">
        <i data-lucide="chevron-left" class="w-4 h-4"></i> Sebelumnya
      </button>
      <button onclick="nextImage()" class="modal-action modal-action-secondary">
        Selanjutnya <i data-lucide="chevron-right" class="w-4 h-4"></i>
      </button>
    </div>
  </div>
</div>

@endsection
