@extends('layouts.public.layout')

@section('content')

<!-- Hero Header Section -->
<section class="hero-bg relative h-screen md:h-[75vh] flex items-center justify-center text-white overflow-hidden -mt-20">
  <div class="relative z-10 text-center px-4 max-w-4xl mx-auto">
    <h1 class="text-5xl md:text-7xl lg:text-8xl font-bold font-serif leading-tight drop-shadow-2xl mb-4 animate-fade-in-down">
      Galeri <span class="text-transparent bg-clip-text bg-gradient-to-r from-emerald-300 to-teal-200">Foto</span>
    </h1>
    <p class="text-lg md:text-2xl text-slate-100 drop-shadow-md animate-fade-in-up">Koleksi momen-momen berharga kegiatan desa</p>
  </div>
  <!-- Scroll Down Indicator -->
  <div class="absolute bottom-10 left-1/2 transform -translate-x-1/2 animate-bounce opacity-80 cursor-pointer hover:text-emerald-300 transition-colors">
    <a href="#galeri-list"><i data-lucide="mouse" class="w-8 h-8"></i></a>
  </div>
</section>

<div class="bg-slate-50 antialiased text-slate-600">
  <!-- Main Content -->
  <div class="container mx-auto px-6 py-12">

    <!-- Filter Buttons -->
    <div class="flex flex-wrap justify-center gap-4 mb-12" data-aos="fade-up" data-aos-delay="100">
      <button class="filter-btn active px-6 py-2 rounded-full bg-emerald-600 text-white font-medium shadow-md hover:bg-emerald-700 transition" data-filter="all">Semua</button>
      <button class="filter-btn px-6 py-2 rounded-full bg-white text-slate-600 border border-slate-200 font-medium hover:bg-emerald-50 hover:text-emerald-600 hover:border-emerald-200 transition" data-filter="kegiatan">Kegiatan</button>
      <button class="filter-btn px-6 py-2 rounded-full bg-white text-slate-600 border border-slate-200 font-medium hover:bg-emerald-50 hover:text-emerald-600 hover:border-emerald-200 transition" data-filter="alam">Alam & Wisata</button>
      <button class="filter-btn px-6 py-2 rounded-full bg-white text-slate-600 border border-slate-200 font-medium hover:bg-emerald-50 hover:text-emerald-600 hover:border-emerald-200 transition" data-filter="pembangunan">Pembangunan</button>
    </div>

    <!-- Gallery Grid - 3 columns -->
    <div class="gallery-grid" id="gallery-container">
      @forelse($galeris as $index => $galeri)
        @php
          $category = strtolower($galeri->kategori ?? 'kegiatan');
          // Map kategori to filter keys
          $categoryMap = [
            'kegiatan' => 'kegiatan',
            'alam & wisata' => 'alam',
            'pembangunan' => 'pembangunan',
          ];
          $categorySlug = $categoryMap[$category] ?? 'kegiatan';
        @endphp
        <div class="gallery-item group relative rounded-xl overflow-hidden shadow-lg cursor-pointer hover:shadow-2xl transition-all duration-300" 
             data-aos="fade-up" 
             data-aos-delay="{{ ($index % 3) * 100 }}"
             data-category="{{ $categorySlug }}"
             data-id="{{ $galeri->id }}"
             onclick="openModal({{ $galeri->id }})">
          <div class="relative overflow-hidden bg-slate-200 h-64 sm:h-72">
            <img src="{{ asset('storage/' . $galeri->gambar) }}" 
                 class="w-full h-full object-cover transform group-hover:scale-105 transition duration-700" 
                 alt="{{ $galeri->judul }}">
          </div>
          <div class="absolute inset-0 bg-gradient-to-t from-white/95 via-white/70 to-transparent opacity-0 group-hover:opacity-100 transition duration-300 flex flex-col justify-end p-6">
            <span class="text-emerald-700 text-xs font-bold uppercase tracking-wider mb-1 drop-shadow-sm cursor-pointer hover:text-emerald-900" data-filter-category="{{ $categorySlug }}">{{ $galeri->kategori }}</span>
            <h3 class="text-slate-900 text-lg font-bold drop-shadow-sm">{{ $galeri->judul }}</h3>
          </div>
        </div>
      @empty
        <div class="col-span-full text-center py-12">
          <div class="text-slate-400 mb-4">
            <i class="fas fa-image text-4xl"></i>
          </div>
          <p class="text-slate-600 text-lg">Belum ada foto galeri</p>
        </div>
      @endforelse
    </div>

    <!-- Pagination -->
    <nav class="pagination" aria-label="Pagination" id="pagination-container">
      <!-- Pagination will be generated by JavaScript -->
    </nav>
  </div>
</div>

<!-- Gallery data for JavaScript (injected as JSON) -->
<script type="application/json" id="galery-data">
{!! json_encode($galeris->map(function($g) {
  return [
    'id' => $g->id,
    'judul' => $g->judul,
    'gambar' => asset('storage/' . $g->gambar),
    'deskripsi' => $g->deskripsi,
    'kategori' => $g->kategori,
    'created_at' => $g->created_at->format('d M Y'),
  ];
})->values()->all()) !!}
</script>

<!-- Modal Lightbox -->
<div id="imageModal" class="modal">
  <div class="modal-content">
    <!-- Modal Header -->
    <div class="modal-header">
      <h2 id="modalTitle" class="text-xl font-bold text-slate-900"></h2>
      <span class="close-modal" onclick="closeModal()">&times;</span>
    </div>

    <!-- Modal Body -->
    <div class="modal-body">
      <img id="modalImage" src="" alt="" class="modal-image">
      
      <div class="space-y-4">
        <div>
          <p class="text-xs font-semibold text-emerald-600 uppercase tracking-wide mb-1">Kategori</p>
          <p id="modalCategory" class="text-sm text-slate-600"></p>
        </div>
        
        <div>
          <p class="text-xs font-semibold text-emerald-600 uppercase tracking-wide mb-1">Deskripsi</p>
          <p id="modalDescription" class="text-sm text-slate-700 leading-relaxed"></p>
        </div>

        <div class="grid grid-cols-2 gap-4 text-sm">
          <div>
            <p class="text-xs font-semibold text-emerald-600 uppercase tracking-wide mb-1">Tanggal Upload</p>
            <p id="modalDate" class="text-slate-600"></p>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal Footer -->
    <div class="modal-footer">
      <button onclick="downloadImage()" class="flex-1 px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition font-medium flex items-center justify-center gap-2">
        <i class="fas fa-download"></i> Unduh
      </button>
      <button onclick="prevImage()" class="px-4 py-2 bg-slate-200 text-slate-800 rounded-lg hover:bg-slate-300 transition font-medium">
        <i class="fas fa-chevron-left"></i> Sebelumnya
      </button>
      <button onclick="nextImage()" class="px-4 py-2 bg-slate-200 text-slate-800 rounded-lg hover:bg-slate-300 transition font-medium">
        Selanjutnya <i class="fas fa-chevron-right"></i>
      </button>
    </div>
  </div>
</div>

@endsection
